export const CHARACTERS_GET20_REQUEST = 'CHARACTERS_GET20_REQUEST'
export const CHARACTERS_GET20_SUCCESS = 'CHARACTERS_GET20_SUCCESS'
export const CHARACTERS_GET20_FAILURE = 'CHARACTERS_GET20_FAILURE'

export const CHARACTERS_SEARCH_REQUEST = 'CHARACTERS_SEARCH_REQUEST'
export const CHARACTERS_SEARCH_SUCCESS = 'CHARACTERS_SEARCH_SUCCESS'
export const CHARACTERS_SEARCH_FAILURE = 'CHARACTERS_SEARCH_FAILURE'